name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
                  registry-url: https://registry.npmjs.org/

            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Build
              id: build
              run: |
                  yarn install --frozen-lockfile
                  yarn build

            - name: Test
              if: ${{ success() || failure() }}
              run: yarn test
